### ISSUE TITLE
Question about Tcal(jy) in ONOFF VAL

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#102]
Just to make this clear to me:
When I measure ONOFF using e.g. Cas A I get a number of VAL lines from ONOFF. 
I am under the impression that Tcal(Jy) is a direct comparison of the noise diode power with the power of the (known reference) source at the sky. Is this true?
For example, if I measure a power increase of 5 units on Cas A, and I know Cas A is 500Jy; and my noise diode power is 1 unit, then my noise diode is 100 Jy. Is this the correct interpretation?
I am confused, because some parts of ONOFF also uses the RXG file to convert and I have lost track of my memory regarding which of these numbers is the converted and which is the raw measurement. 
The Tcal(r) ratio between the measured diode and the diode level in the RXG file is reasonable. Here the DPFU is needed to convert between the tabuleted values in Kelvin to Janskys. But: is the Tcal(j) showing the measure value compared with the sky, OR the converted value from the RXG file? 

I'm sure this is written somewhere, because I have found it before, but now I couldn't.

**Comment by wehimwich** [comment]
Yes. Tcal(Jy) is a level of the cal signal to compared to the source, expressed in Jy.

I believe your example with Cas A is correct.

The Comp, SEFD, and Tcal(Jy) values are independent of the _.rxg_ file values.  The Tsys value depends on Tcal from the _.rxg_ file. The SEFD and the Tcal(Jy) depend on the flux from the _flux.ctl_ file. Lastly, for Tcal(r): the DPFU and the gain curve from the _.rxg_ file are used to convert Tcal(Jy) into Tcal(K), which is then divided by the Tcal value from the _.rxg_ file. It is a sort of a figure-of-merit for the current _.rxg_ file information. Close to unity is best of course.

Tcal(Jy) is compared to the source in the sky, not using the _.rxg_ file. Keeping it simple. The Tcal(Jy) values are the fundamental data for _gnplt_.

I expect it is in the _onoff_ manual, which is out-of-print and you may have never seen. Maybe there are old copies lurking around Onsala and/or Jodrell. The other place would be the TOW notebooks. We are working on getting the manuals back in print, but it is slow going.

I am interested in hearing how useful Tcal(r) is for evaluating the calibration and how much spread is seen with good calibrations. RFI of course can bollix it up.

**Comment by varenius** [comment]
Thank you for the nice explanation. Two comments

- Re Tcal(r) usefulness: I use this every experiment and I find it extremely useful. It is a very quick measure of the full signal chain and setup, and easy to check as part of setup procedures.
- Re Tcal(j). Thank you for clarifying. I have thought long and hard about this, and confused myself many times. But I think I have now converged. 
Therefore I want to make the point that given the way that Tcal(j) is measured, i.e. by directly comparing with the source (without RXG info applied), then strictly speaking this level can be said to not be in Jansky, but in some "Jansky * gain" unit. Because, the measurement of Tcal(Jy) compares the diode to an external signal (from the source) which is affected by the gain of the antenna. Put another way; two diodes with the same power measured in the lab will not give the same Tcal(Jy) when measured against the same celestial source if they are mounted in two telescopes with different gain. This is a bit weird conceptually: two identical things when compared against an identical reference (e.g. Cas A) will given different answers. As long as this is understood, it is no problem to uset the Tcal(Jy) as a reference for SEFD vs time logging, but it confused me for some time. Notably, one can assume some DPFU (e.g. 1) measure the Tcal(Jy), measure the relative gain (vs elevation) and put all of this consistently in the RXG file. But, then the Tcal(Jy) must refer to the level measured at the peak gain elevation, or the DPFU/Tcal abslute level must be adjusted. (For VGOS stations, the gain is very flat across elevation, but it's still a reduction due to efficiency eta <1.) Easy enough to do with e.g. gnplt2.
So, perhaps - if there at some point is some updated documentation for ONOFF released (or in the help file) - it could be noted that Tcal(Jy) is derived by comparing against the celestial source which is affected by any antenna gain.

**Comment by wehimwich** [comment]
I am glad to hear Tcal(r) is useful. I am also interested in how much variation is seen. This may well depend on the SEFD and RFI. I suppose a way to look at this is to examine the values from an _aquir_ run with a good _.rxg_ file already in place.

I tend to think of the SEFD as the verification of the system. The Tcal(r) won't tell you if the system is warm. It will only tell you if the combination of gain and noise diode level is different than expected. That is a useful thing in itself, but secondary to SEFD. That is not affected by the noise diode level, just system temperature and gain (including the gain curve).

I am probably stating the obvious, but the Tcal(j) value is just trying to answer one question: if I compare the power level of the diode to this source using this antenna at this time, elevation and frequency, what is its equivalent power in Janskys? The point of the _gnplt_ analysis is to model the variation in Tcal(j) as a DPFU, gain curve, and (apparent) noise power variations (for the latter as a function of frequency). As we have agreed, as long as that model is correct to a scale factor, you can calculate the SEFDs from the raw power measurements. 

To beat the "don't use Tsys" drum one more time:  It is difficult to accurately measure system temperature because it is hard to measure the _effective_ noise temperature of the diode accurately. Fortunately it isn't needed for our purposes, just a rough value will do. That value sets the scale factor of the _.rxg_ file model. To get SEFDs from accurate Tsys values, you would still need the DPFU and gain curve as well of course.

I agree we should make this more explicit in the documentation; for now we have this issue on github. :) It should also be covered, if it isn't already, in the TOW presentation on calibration. The TOW presentations are a useful adjunct to the FS manuals, not least because they are more up to date, but also more available.
