### ISSUE TITLE
Plog won't process a log if being viewed by tail -f

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#106]
GGAO (KP) reports that _plog_ gives up if the log is being viewed with `tail -f`. It is not clear what this is trying to protect against. The _fuser_ program that detects the access does not detect if _ddout_, or _vim_, has it open, which might be a more serious issue since they can write to the file.

**Comment by wehimwich** [comment]
Maybe this has to be viewed from the point-of-view of _tail_. If it has locked the file, it is rude for another program to change it. If a program has the file open, but didn't lock it, _plog_ has no way to know that what it wants do is rude (kind of a slippery slope of making excuses). I suppose the solution is to subscribe to the log stream (e.g. `ssub ws://127.0.0.1:7083/log`) to get the functionality of `tail -f` for the active log, or for many purposes the display stream may be good enough (`fsclient -n`). I don't see a solution for _less_. Maybe that is just something to be aware of.

One could imagine having _ddout_ lock the log file to prevent _plog_ from pushing it until it is closed, but that seems too proscriptive.

**Comment by dehorsley** [comment]
Ah I did a bit of git-blaming. We introduced this to prevent someone ploging a file while it was still open  because *plog* will move the log if it's going to make a "reduced" log. This was mostly for *ddout* as I think *plog* moving the file triggers *ddout* to try to recover the log, overwriting the reduced log.

Odd the *fuser* call isn't picking up that ddout has it open. I thought this worked.

More on topic, it does seem a bit strange for *less* or *tail* to prevent uploading a log. Perhaps the check in plog should just look for ddout?  Triggering the recovery seems to be the biggest problem we're trying to avoid. Anyone who has the log open in vim or the like should know what they've got themselves into! (Also vim will warn that the file has changed since last opened before overwriting.)

**Comment by wehimwich** [comment]
Good catch!

I think the fly in the ointment is that locking is cooperative and _ddout_ is not cooperating (by locking the file). This locking stuff is new material for me.

I was being overly sensitive. :) OTOH, it is necessary to be proscriptive in this case.

 PR coming shortly.
