### ISSUE TITLE
gnplt autoscales wrong with VGOS Tcal vs Freq when selecting "Tools--> Plot from file"

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#117]
I want to plot Tcal vs frequency. I also want to see the Tcal values from the current RXG file. I try this:

gnplt, open file, Edit--> Delete bad GC points
Edit -- Tcal vs freq --> Left, All, 0-14 GHz.
I obtain this figure on screen, which covers 3-11 GHz data:
<img width="963" alt="Screenshot 2021-04-29 at 11 44 41" src="https://user-images.githubusercontent.com/8872291/116532594-b3f12c80-a8e0-11eb-8e87-a0fb7051f2cd.png">
Now I want zoom into the 5GHz part, so I see this:
<img width="965" alt="Screenshot 2021-04-29 at 11 45 07" src="https://user-images.githubusercontent.com/8872291/116532626-bce1fe00-a8e0-11eb-8260-c8668b2c00f9.png">
Then I select Tools --> Tcal from working file. I now get this:

<img width="963" alt="Screenshot 2021-04-29 at 11 45 27" src="https://user-images.githubusercontent.com/8872291/116532637-bf445800-a8e0-11eb-9587-24dbd1475216.png">

Surprises:
- It does not show 11GHz. Why?
- I only wanted to see my zoom region, but now I'm zoomed out. If I zoom in again on my 5GHz points, then the "Tcal from file" curve disappears. So I don't see a way to look at the 5GHz (VGOS band B) data with the model. I suggest that either adding the model does not trigger a replot, and/or that the model is included until deselected or a new dataset (e.g. tcal fs freq) is loaded.

**Comment by varenius** [comment]
I meant to attach a short logfile to reproduce the plots above, but forgot. Here is the log!
[ottn_small.log](https://github.com/nvi-inc/fs/files/6398242/ottn_small.log)

**Comment by wehimwich** [comment]
Thanks for the log. When I get a chance to look at this, I will also need the _.rxg_ file(s) involved. Could you please attach them also?

**Comment by varenius** [comment]
Here is the RXG file (I had to rename it to .txt for github).
[ottn.rxg.txt](https://github.com/nvi-inc/fs/files/6400651/ottn.rxg.txt)

**Comment by wehimwich** [comment]
Thank you for providing a test data set with instructions for reproducing the problem.

> Surprises:
> - It does not show 11GHz. Why?

That looks like a bug to me. It wants to show the full Tcal curve, but was not rescaling for the maximum frequency value. The bugs seems to be more general, but apparently only comes up when plotting the working file Tcal while zoomed in.

I have a tentative fix. There is one case that it affects, plotting fitted Trec, that I can't test very well with the small elevation range in this data set.

> - I only wanted to see my zoom region, but now I'm zoomed out. If I zoom in again on my 5GHz points, then the "Tcal from file" curve disappears. So I don't see a way to look at the 5GHz (VGOS band B) data with the model. I suggest that either adding the model does not trigger a replot, and/or that the model is included until deselected or a new dataset (e.g. tcal fs freq) is loaded.

I think it has always been (and probably always will be) a "feature" that added "decorations" like the Tcal curve are lost when the plot is redrawn. 

I have a change so that it will only plot the working file Tcal curve for the tabular points that occur in the frequency range that is currently displayed (making the previously mentioned bug fix irrelevant), resizing the vertical axis as needed. I think this is similar to the Tcal fitting functions which, I think, only fit over the data displayed.

Anyway, I  have a made a pull request (#127) for you to look at.  It would be helpful if someone with opacity/Trec experience could test the fitting of Trec to verify that the plotting is still okay.

**Comment by wehimwich** [comment]
Thanks. It tuned out that I already had that log. I guess from previous issue resolution :)

So the Tsys-Tspill plot posted before is of course absurd. That is because the PR still had the "greater than 20 detectors" issue that was solved for issues #107 and #104. I rebased the PR on master and now it plots okay:

<img width="994" alt="Screen Shot 2021-08-29 at 11 07 24 AM" src="https://user-images.githubusercontent.com/51408905/131255654-111b8db0-2b8b-4dfa-a20e-f628d0ffef9b.png">

The fit is for a 24h data set. Perhaps not the best analysis, but I think that it shows that the functionality is working. It does zoom okay on this plot, as well as the original Tcal plot that started this thread.

I think it is finished. If you could verify that, it would be great. You will need to delete your branch for the PR, fetch, and checkout the new version.

**Comment by varenius** [comment]
I think this is indeed finished now, thanks. I cannot verify this easily right now, but given the clarity of "this fixes that" in this issue I'm fairly confident you sorted it all. Good work, I think this can all be pushed into master now, and this closed!
