### ISSUE TITLE
fspgm.ctl

### ISSUE THREAD

**Issue by stuartdweston** [nvi-inc/fs#130]
Modify entry for _oprin_, the `-name` parameter doesn't like being changed !

```
oprin x xterm -fn 10x20 -geom 80x5+10+520 -name oprin -j -e oprin -fs_internal &
```
If I change : 

```
-name oprin
```
to something else like 

```
-name Operator-Input 
```
or 

```
-name "operator Input" 
```
I get the following in the err file : 

```
getting ddout
getting fserr
running incom
getting boss
getting matcn
getting mcbcn
getting chekr
getting ibcon
getting fivpt
getting onoff
getting quikr
getting quikv
getting moon
getting pcalr
getting setcl
getting aquir
getting antcn
getting rclcn
running oprin
cls_chk: class 1 not allocated
cls_chk error 1 in cls_rcv()
ddout terminated-Exit code 255
oprin terminated-Signal # 124-core dumped
fserr killed
boss killed
matcn killed
chekr killed
fivpt killed
quikr killed
setcl killed
rclcn killed
mcbcn killed
ibcon killed
onoff killed
quikv killed
moon killed
aquir killed
antcn killed
pcalr killed
```

**Comment by stuartdweston** [comment]
It seem's to conflict with : 

-e program [ arguments ... ]
    This option specifies the program (and its command line arguments) to be run in the xterm window. It also sets the window title and icon name to be the basename of the program being executed if neither -T nor -n are given on the command line. This must be the last option on the command line. 

I have tried -T -title and -n and I get the same error

**Comment by wehimwich** [comment]
That is right, _fspgm.ctl_ does not like being changed. It is a core part of the FS. You should avoid routinely changing anything in _/usr2/fs_. For running station specific programs, you should normally only change _stpgm.ctl_ and _clgpm.ctl_, both in _/usr2/control_.

For each _xterm_ run by the FS, its resources are defined in your _~/.Xresources_, for an example see _/usr2/fs/st.default/oper/.Xresources_. This allows the stations to customize things like the geometry, title, font, etc. for these windows without changing the FS source. Each _xterm_ used by the FS has a `-name` parameter (for example for _oprin_: `-name oprin`) that is used by to look up the resources. All the resources specific to _oprin_ in _~/.Xresources_ use the `oprin` name. The default window _title_ for _oprin_ is `Operator Input`.

On the console X display, the _~/.Xresources_ file should be loaded automatically when you login. If you connect from another display with _ssh_, you can load it manually from _bash_ with:

````
xrdb -merge ~/.Xresources
````

There is an alias, `rlxr`, for that defined in the example _/usr2/fs/st.default/oper/.bash_aliases_ (your working copy is in _~/.bash_aliases_).

You could instead modify your _~/.profile_ to  to load it it at login, perhaps conditionally depending on the display.

You can also define other X resource files and aliases for other displays, maybe _~/.Xresources_mac_ and `rxlr_mac` for your Mac(?), adjusted the resources as appropriate. Being able to customize for different displays is an advantage to having all the resources defined in X resource files instead of on the command lines.

For tips on setting `geometry` values in X resources files to make layout repeatable, please see: [Setting geometry values in .Xresources](https://nvi-inc.github.io/fs/releases/misc/install_reference.html#_setting_geometry_values_in_xresources).
