### ISSUE TITLE
Surprising amount of FS complains DBBC3 multicast lost during vo1245

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#140]
I think this is one for me to investigate locally in Onsala, but for now I'm logging it here as it may be of interest elsewhere.

**Background:**
We rely on multicast for many telescope monitoring systems in Onsala, and we never have any issues. Therefore I was a bit surprised to see the FS complain with "ERROR dn  -20 DBBC3 multicast: no message received, multicast may not be running" every now and then. I left the FS sitting doing nothing for a few days, just to log the frequency of this errors. It seems to be around 60-80 per 24h:
```
oper@freja:/usr2/log$ grep "ERROR dn  -20 DBBC3" dbtt.log | grep "2021.249." | wc -l
60
oper@freja:/usr2/log$ grep "ERROR dn  -20 DBBC3" dbtt.log | grep "2021.248." | wc -l
83
```
This is surprising, but could perhaps be waved away blaming UDP etc. (Still I'm surprised about this). The frequency is then about 3 failures per hour, which we can live with if that means losing TPI for a few seconds. (Since the FS was not running a schedule, there were not TPI values written to the log so I could not check if this was actually lost.)

**Problem:**
During experiment vo1245, the FS complains EVERY SCAN about the multicast being lost:
```
oper@freja:/usr2/log$ grep "ERROR dn  -20 DBBC3" vo1245ow.log | wc -l
1301
```
This is not reasonable. I suspect either
a) Some system/FS call executed during the experiment procedures is disturbing the multicast reception, or 
b) some inherent issue with FS receiving multicast is made worse by the schedule, but could perhaps also explain the 3/h frequency in the "doing nothing" state described in the background section.

I will now look at the vo1245 logfile (which is also at IVS) in detail to see if I can find a trigger for the mcast errors.

**Comment by varenius** [comment]
Found the trigger already. In our "midob" procedure we have a line"dbbc3=time". Everytime I run this command, the FS complains about losing the multicast. Here are two executions which both trigger this:
```
2021.250.09:11:48.51;dbbc3=time
2021.250.09:11:49.61?ERROR dn  -20 DBBC3 multicast: no message received, multicast may not be running
2021.250.09:11:50.79#dbbcn#dbbc3/time/
2021.250.09:11:50.79#dbbcn#dbbc3/time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:49
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:49
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:49
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:49
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:49
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:50
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:50
2021.250.09:11:50.79#dbbcn#dbbc3/FiLa10G % time
2021.250.09:11:50.79#dbbcn#dbbc3/2021-09-07T09:11:50
2021.250.09:11:50.79/dbbc3/FiLa10G % ;
2021.250.09:11:51.36?ERROR dn   20 DBBC3 multicast: receiving multicast messages again.

2021.250.09:11:58.64;dbbc3=time
2021.250.09:11:59.61?ERROR dn  -20 DBBC3 multicast: no message received, multicast may not be running
2021.250.09:12:00.76#dbbcn#dbbc3/time/
2021.250.09:12:00.76#dbbcn#dbbc3/time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:11:59
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:11:59
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:11:59
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:11:59
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:11:59
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:12:00
2021.250.09:12:00.76#dbbcn#dbbc3/time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:12:00
2021.250.09:12:00.76#dbbcn#dbbc3/FiLa10G % time
2021.250.09:12:00.76#dbbcn#dbbc3/2021-09-07T09:12:00
2021.250.09:12:00.76/dbbc3/FiLa10G % ;
2021.250.09:12:01.36?ERROR dn   20 DBBC3 multicast: receiving multicast messages again.
```

(I note that in the second test above, one of the "FiLa10G % time" responses somehow gets split in "2021.250.09:12:00.76#dbbcn#dbbc3/time" and "2021.250.09:12:00.76/dbbc3/FiLa10G % ;" which is weird, but that seems rare and unrelated?)

So, the question is: Is the DBBC3 unable to keep the multicast running while it is being asked for the "time", OR is the FS unable to receive the multicast when parsing the response from the DBBC3?

This could be investigated using the external multicast dump script provided with the DBBC3. Running this in paralell with the FS; it proves that whenever I send the "time" query to the DBBC3, also the external multicast pause for about 3 seconds. So, the FS appears to be innocent of these regular vo1245 multicast drops?

I tested some other commands:
- Multicast OK: "dbbc3=dbbcifa" and "dbbc3=dbbc001"
- Multicast fails: "dbbc3=core3h=1,vdif_frame", "dbbc3=core3h=1,vsi_bitmask"

I will ask the DBBC3 developers about this behaviour.

**Comment by varenius** [comment]
Sven (DBBC3 developer) replied:

> some of the commands are using a direct communication with the Core3H or ADB3L boards.
> This requires to stop the control loop that is using the direct communication to aquire the
> data that is send out via multicast. So this is not a bug, but a necessary precaution to prevent
> an I/O conflict.
> 
> In future versions starting with DDC_U v126 there will be less commands using the direct communication,
> so commands like time or core3h=... will not stop the multicast any more.
> 
> But for other commands like the calibration routines this will always be the case.

I think this should be fine. We only use "dbbc3=time" for monitoring now, no other command is sent regularly during scans. In later firmware versions, the multicast should contain the VDIF time, and hence the time-command is redundant.

I think this can be closed now.

**Comment by wehimwich** [comment]
There are a few things to comment on here.

As Sven said when the command channel is busy, the multicast seems to stop. Apparently, it is not delayed; it stops. I haven't gone through and identified all the commands where this happens, but I think they include at least the Core3H commands and the `time` command.

This error comes up most often when the FS is setting or checking the setup of the DBBC3. The _drudg_ generated `setup` procedures turn off multicast logging when they start (with `tpicd=stop`) and back on (with `tpicd`) when they finish. Ostensibly, this is done because the configuration may be inconsistent during this period. I added to `tpicd=stop` that is disables reporting multicast errors until the they are reenabled by `tpicd`. This gets rid of these "extraneous" errors during `setup` procedures.

A side effect is that you could suppress the errors in `midob` by bracketing any monitoring commands that cause a problem with `tpcid=stop` and `tpcid`. You probably won't be getting any logging during that period due to the lost messages anyway. Even if a few extra are lost that way, presumably that would not a problem unless the scan lengths are very short, say 10 seconds. In that case, you would probably not want to include any monitoring commands that cause this problem in `midob` at all. I will add the method for silencing multicast errors in midob to the **NOTE** in [Multicast logging](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_multicast_logging)

Another aspect of this is that when the FS is first started, it will report any multicast errors. That seemed better than there being an invisible problem. If you start using various commands trying to test something, you may get these annoying multicast errors. You can do a `tpicd=stop` at that point to suppress them. They can be reenabled at any time by setting up and starting _tpicd_.

BTW, when the errors are suppressed, the Tsys monitor display will still display the most recent information received in the multicast. It might get "jumpy" though if there are missing messages.

Monitoring  the time is a special case. There is a new command `mcast_time` that will log the time from the latest multicast message, telling you how old it is and what the corresponding FS time was. I think that is a much better choice for time monitoring and executes essentially instantaneously.

I am interested in the three failures per hour when the system is quiescent. That is only about 0.1%, which isn't too bad. We had a situation at a station where the dropped multicast from the RDBEs was a few percent. That turned out to be  due to an issue with a piece of network equipment. I think when I was testing on _njord_ that you had the multicast on the second NIC. Is that the case here? If so, is there anything beside the multicast on that NIC? In any event, maybe the external dump program could be used to check if it misses the same messages. You would need to turn the multicast logging on the FS to make a record for that.
