### ISSUE TITLE
When do we get "equip" and when "equip1" in the FS log?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#144]
I'm pondering modifications to https://github.com/evn-vlbi/VLBI-utilities/blob/master/antabfs.py which can read the "equip" line in the FS log to parse DBBC personality (PFB/DDC). Example log line from our FS10 S/X system with DBBC2:
```
2021.265.11:50:50.14;equip,dbbc_ddc/fila10g,flexbuff,none,mk4,500.10,3,a/d,101,60,30,none,40,1,in,8bit,cdp,3,return,v107,v16_2,1,1,1,1,15000,15000,15000,15000,128,vsi1-2,v121,16,8
```
In the DBBC3 system, I instead find these two lines:
```
2021.266.11:25:15.20;equip1,dbbc3_ddc_v,flexbuff,none,none,500.10,3,a/d,101,60,20,none,40,1,in,8bit,cdp,3,return
2021.266.11:25:15.20;equip2,v107,v15_1,1,1,1,1,15000,15000,15000,15000,128,vsi1-2
```
Do we always get two equip lines with DBBC3? OR, have I misconfigured something? And: can we get two equip lines also with DBBC2 in some situation (e.g. with two DBBC2s)?

**Comment by wehimwich** [comment]
This is a change made in the `ed/dbbc3` branch. I forgot to add that to the [draft DBBC3 Ops document](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html), but have now (thanks).

I thought the long `equip` line was unsightly, so I broke it into two parts. This anticipates possibly eventually moving most of the contents of the `equip2` line to a new _dbbc.ctl_ control for DBBC(2) values. I had hoped to do that with this version as well. This is a little tricky though because the clock rate entry (`128` on the line you quote for `equip2`) is not unique to the DBBC2, yet the interpretation of the `nominal` value for that entry in _equip.ctl_ can depend on the DBBC(2) firmware version.

To answer your questions: In this branch and in the released version of FS once the branch is merged in, you will always get `equip1` and `equip2` regardless of the equipment. Well, unless I can figure out how to organize it so we can have a separate _dbbc.ctl_ control file before the merge (maybe a nice hot cup of tea and a quiet room would help, suggestions are always appreciated, maybe it is a bad idea anyway, says Arthur/Marvin).

This doesn't depend on having two DBBC(2)s in any way. A second DBBC(2) is not fully supported. There are just some ad hoc extensions to make it possible to record current VGOS data with a dual DBBC(2) configuration. There is some more detail on this under item (8) of [FS10 changes relative to the old main branch](https://nvi-inc.github.io/fs/releases/10/0/changes_10.0.0.html#_fs_changes_relative_to_the_main_branch).

**Comment by wehimwich** [comment]
After discussion with @jfhquick, I decided to just make a new DBBC3 only clock rate in the _dbbc3.ctl_. That will at least not burden the clock rate in _equip.ctl_ wiith yet another use.

A possible path for handling the joint Mark5B/DBBC(2) clock rate might be to have both. If a DBBC(2) rack is specified the clock rate in a _dbbc.ctl_ control file could override a Mark5B rate, whether the latter is in _equip.ctl_ or a (new) _mark5b.ctl_ control file. That would be a little tricky, but maybe it is clear enough. The appropriate time to make the change may be as part of a more general clean-up of _equip.ctl_. I'll keeping thing about this. Additional comments would be appreciated. 

This is a bit off-topic for this issue, which I think has been addressed. I am closing this issue. It can be reopened or a new issues started as seems appropriate.
