### ISSUE TITLE
DBBC3 core3h_modeX command behaviour - what should be allowed per firmware version?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#145]
Testing DRUDG for DBBC3 on vo1259 for Oe I get an S/X schedule which contains
```
define  core3hsx      00000000000x
core3h_mode0=begin,$
core3h_mode1=,0x51111115,,16.0,$
core3h_mode2=,0x00111111,,16.0,$
core3h_mode0=end,$
```
This wanted definition could meet several realities:

- Case 1: The DBBC3 has already been configured like this, for example like boot time. In this case, running core3hsx will only report all is fine. However, running core3hsx=force will destroy the timing on DBBC3 DDC v124 firmware, without any obvious FS way to rectify (please correct me if I am wrong). Hence, running core3hsx=force will in this case destroy a working existing configuration.
- Case 2: The DBBC3 has been configured with the correct bitmasks for core3h cards 1 and 2, and these are sending data, but there are also other cards with data flow enabled which should not send data. Running core3hsx=force will destroy the timing as noted above. However: Running the following twice:
```
core3h_mode0=begin,force
core3h_mode1=,0x51111115,,16.0,$
core3h_mode2=,0x00111111,,16.0,$
core3h_mode0=end,force
```
where "force" is only used in the core3h_mode0 commands, will first produce errors for boards 3,4... about "output started", but the "end,force" will turn these off. The second time we run the above, both bitmasks and outputs will be correct, and no complaints voiced. So, actually, although we're not allowed to destroy the timesync with this firmware, we *could* be allowed to change the data on/off.
- Case 3: The DBBC3 has been configured with the wrong bitmasks for the relevant cards (1,2). In this case, one would need to (my understanding) reboot the DBBC3 with the proper bitmasks.

Thoughts:
- It seems to me that if running "force" on core3h_modeX where X!=0 is doomed for this firmware, perhaps it should not be allowed? Or is this too complicated, and we should just assume everyone will get the new firmware (126?) where this will be working?
- I have only tested v124. v125 is available but I don't remember the status: is it like v124 in terms of "FS cannot do timesync"?
- I seem to remember v126 should allow for a new timesync command which could be used by FS. If so, this should be coded into the core3h_modeX commands.

**Comment by wehimwich** [comment]
My feeling is that in Case 2, if you are going to rely on the booted configuration, it might as well set the correct data on/off as well, assuming that is possible.

If there will be a significant amount of mode changing that can be accomplished just by turning boards on/off, we can look into another option but otherwise I don't want to complicate things too much. You can, as noted in the [Starting data transmission](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_starting_data_transmission) subsection of the draft manual, start and stop data transmission outside of the `core3h_mode0=end,force` command. Normally, you don't want to do that since it would then cause the configuration to disagree with your mode. However, if you did this to make the configuration _agree_ with a new mode, then the new mode setup procedure run without `force` would check the setup correctly. Maybe that would be enough until we see that this is needed more generally.

> Thoughts:
> 
> - It seems to me that if running "force" on core3h_modeX where X!=0 is doomed for this firmware, perhaps it should not be allowed? Or is this too complicated, and we should just assume everyone will get the new firmware (126?) where this will be working?

Well, I don't know that is doomed. I know Sven doesn't like it, but I think you, at least, have some success re-syncing. As a result, I am reluctant to not allow it. Also, I don't know that v126 will fix this problem. It may give us a DBBC3 command that will provide reliable re-syncing, but until we see how it works and how best to incorporate it into operations, I don't want allow `force` for v126 and not for v124/v125. Hopefully, as you suggest below, the FS could command re-syncing as part of `core3h_mode0=end,force`.

> - I have only tested v124. v125 is available but I don't remember the status: is it like v124 in terms of "FS cannot do timesync"?

That is my understanding.

> - I seem to remember v126 should allow for a new timesync command which could be used by FS. If so, this should be coded into the core3h_modeX commands.

Yes, that would be great.

**Comment by wehimwich** [comment]
It seems like since the previous comments were written, we aren't expecting an acceptable DBBC3 sync command until the next round of versions, possibly v130. This topic can be readdressed then. For now I think the word is that the DBBC3 should only be synced at boot. BTW, also since the above comments were written, the use of `force` is now used to collect the information for setting the DBBC3 boot configuration for the scheduled mode as described in [Setting the experiment mode configuration](https://nvi-inc.github.io/fs/releases/10/1/dbbc3_ops.html#_setting_the_experiment_mode_configuration). Otherwise, the `core3h...` procedures, not using `force`, are for checking the configuration. Lastly (and least), the `core3h_modeX=...` commands are now `core3h_mode=X,...`.
