### ISSUE TITLE
DBBC3 DDC_U v125 using 128 BBCs, I still only get 64 BBCs in the DBBC3 Tsys monitor window?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#149]
As title says, it seems I only ever get 64 BBCs even if I'm using and setting 128 BBCs with DDC_U v125. Did I forget some setting for the DBBC3 tsys window?

**Comment by wehimwich** [comment]
There is an issue, #24, about resizing the _monit_ windows. I suppose it is only considered a cosmetic issue because generally the windows only have a fixed size and are usually opened with that size according to what is set in _~.Xresources_. The DDBC3 Tsys window could well be the only exception to that since you could use the size for 16 BBCs/IF all the time, but when you are only use eight, you might want to recover the screen real estate.

I believe resizing will make not make a jumble if you are reducing the size of the window to the space actually being used. Starting it with room for 16 BBCs/IF and shrinking it down for eight would probably work okay.

I am closing this issue for now. Related issue #24 is still open.
