### ISSUE TITLE
Tsys from the continuous calibration

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#157]
### Discussed in https://github.com/nvi-inc/fs/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **vlbi-jun-yang** November  4, 2021</sup>
In case of the 80 Hz continuous calibration, it seems that the FS Tsys estimate excludes the contribution of the noise sources.  Is my understanding correct? </div>

**Comment by vlbi-jun-yang** [comment]
To add TCal/2 into Tsys, one has to consider another the case of negative Tsys caused by the DBBC2 firmware bug of cont_cal in some BBCs. I was to told to repeatly run cont_cal=off and cont_cal=on for a few cycles to get positive Tsys in all the BBCs. In practice, it might require more than 10 cycles. This was a rather disappointing experience.  So, one may have to live with negative Tsys if the problem cannot be fixed rapidly. 

On the safe side, it is better to take the absolute value of Tsys and then add  TCal/2 to the final Tsys.

**Comment by vlbi-jun-yang** [comment]
All right. This is much simpler than I thought. Great.

**Comment by wehimwich** [comment]
We received verification from Javi that the downstream processing uses the raw count data. So this issue should not affect amplitude calibration. In fact, he reported that there is an offset between _antabfs_ and FS values of about the expected size and sign. 

I don't think this issue would be a significant effect for routine station performance checks using Tsys. Of course, I am willing to be disabused of that thought.

It may affect some specialized measurements. If there are any of those, hopefully the impact is low since the error is fairly small. We’ll have to see what people report.
