### ISSUE TITLE
Unable to connect to server: Timed out

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#178]
Christian (Wettzell) reports the following error when trying to restart the FS after terminating it:

![image001](https://user-images.githubusercontent.com/51408905/167207218-af63c590-387b-4fce-9a5f-2d10eadc3cf0.png)

This appears to be a failure from `nng_dial()`.

A Debian _9.13_ (FSL10) system is being used. An unusual aspect of the installation is that it is running in a VirtualBox. 

Generally _kill_ has to be used on _fsserver_ to recover. A reboot ("shotgun" style) does not fix it. That is, it will fail again on the second FS start after a reboot. Another possible path, using _fssever stop_ after terminating the FS, produces a similar error:

![image002](https://user-images.githubusercontent.com/51408905/167208272-760cf27e-af4c-4027-9eba-f279927b1cc9.png)
 
Again, apparently from `nng_dial()`.

For now, the commits from PR #176 are available on branch `ed/wettzell` for testing to see if that helps.

**Comment by dehorsley** [comment]
The server still running when they get this error? Are there any messages in the "fsserver.err" file?

**Comment by wehimwich** [comment]
From that state, the server has be killed before the FS can be restarted. I will ask about any fsserver.err files again. I sort of suspect there aren't any, but it is certainly worth verifying. I may be able to test remotely. If there are no other leads, I might look into installing the VM. If you have any suggestions for what to look for, I am all ears.

**Comment by wehimwich** [comment]
Christian sent the _fsserver.*.err_ files he has. They are alternately empty or contain:

> fsserver.c:394 (server_main) error error starting server: Address in use

**Comment by dehorsley** [comment]
They're using the latest version of the FS? And the version of NNG we ship with? No other modifications?

> They are alternately empty or contain:
>
>>    fsserver.c:394 (server_main) error error starting server: Address in use

That's unfortunate, but not surprising. The `fs` program uses `fsclient` to check if the server is running, since it's timing-out, `fs` will try to start the server and connect to it.

It sounds like the server is locking up, but it's hard to know why. Especially as we aren't seeing this elsewhere. I doubt it's because of the VM, I've never had a problem running in VMs (QEMU). Attaching to the sever executable with a debugger would help. Or getting a core dump.

**Comment by wehimwich** [comment]
Thanks. That was helpful. Presumably the server is locking up somewhere after the FS terminates. On my system, I am able to set breakpoints and stop in `server_sigchld_cb()` and `server_main()`. If the problem doesn't go away with debug compile options for the system at Wettzell, maybe we can look around there.

The _10.1.0-beta2_ version was being used when these errors occurred. Anecdotally,  this problem was not observed with _-beta1_. These are infamous last words, but nothing changed in that area between _-beta1_ and _-beta2_, so I sort of doubt that it is a _beta2_ issue. Maybe we  can test that too.

**Comment by ubach-ef** [comment]
Hi, Wettzell is actually not the only system. I've the same here in Effelsberg. I didn't mention this so far, as I also still have problems with my old station code that is not working with the 64-bit system. I thought that the server is hanging because of some problems with the station code. I had this problem also with the beta1 version. The FS PC here is also a virtual machine with Debian 10.5 (Linux fs10pc 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64) running in a virtual box. I probably should have mentioned that earlier.

**Comment by wehimwich** [comment]
The plot thickens. Thank you for the additional clues. Another factoid: this issue does not appear to be present on a _Bullseye_ hardware system (5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64), with no station code.

**Comment by dehorsley** [comment]
Thanks Uwe. Did it also happen with version 10.0.0?

 These's only been 815b1a4ed committed to the server directory since then. If 10.0.0 works, then that would narrow it down a bit. Not that I see anything suspect in reviewing the commit.

**Comment by wehimwich** [comment]
I've been testing with Christian's system. I can confirm that this issue also occurs with the commit before 815b1a4ed.

**Comment by wehimwich** [comment]
I installed VirtualBox on a Mac with Bullseye amd64. It exhibited the same time-out. Christian reported that he had VirtualBox on a WinPC with Stretch amd64. Uwe also reports he was using VirtualBox, I think on a Debian system.  I don't know why VirtualBox would be the issue, but it is in common for all the cases with this problem.

I am waiting for some more details from Uwe. It may be that this problem did not occur with Wheezy (i386 probably) and/or pre-FS-10.0.0. There may be more cases worth trying to narrow it down.

**Comment by dehorsley** [comment]
OK, I think I understand the problem. The deadlock is coming from my logic, but the locks are in the library. 

The reason the deadlock occurs on the VMs is because of the number of cores available. The library allocates a number of worker threads based on the number of CPUs. With only 1 core, there are only two worker threads. The bug occurs as both are waiting for a cleanup the closed fs "window", which needs a third thread.

I'll look at getting a patch out in the next week. As a workaround, you can bump the number of virtual CPUs up on your VMs .

**Comment by ubach-ef** [comment]
Hi, it works for me as well. I've increased the CPUs to two and the fsserver starts and stops fine. Terminating and restarting works without any problems. I'll just leave it with two CPUs for now. My first impression is that the VM actually runs better as well with two CPUs. Thanks!

**Comment by wehimwich** [comment]
Christian confirmed that it worked for him as well.

**Comment by wehimwich** [comment]
I am not sure we need a fix for this. It could just be a feature that for a VM, you need more than one core to use the server. Unless a patch is in the offing, I am inclined to close this for now. We can add an explanation about this to the installation notes and at the FS server documents.

**Comment by wehimwich** [comment]
The need for at least two cores was added to the [Motherboard setup section of the FSL11 Installation instructions](https://nvi-inc.github.io/fsl11/#_motherboard_setup).
