### ISSUE TITLE
Add option to fesh for verbose curl/wget output

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#201]
Last week fesh started giving errors like this on the Oe/Ow (but not On !) Field-Systems:
```
oper@freja:~$ fesh -f rv159
[fesh 2022-04-30]
Fetching schedule from server...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (8) Got a 530 ftp-server response when 220 was expected
```

Changing /usr2/oper/.profile from `export FESH_DATA_CENTER=bkg` to `export FESH_DATA_CENTER=cddis` solves the problem, but I'm curious to know why it works on one machine and fails on 3 others. They all run the same FS version with the same .netrc details for BKG. There must be some other config difference; any idea where I could look?

**Comment by wehimwich** [comment]
Are you using `export FESH_BKG_METHOD=ftp` on Oe/Ow and not on On?

**Comment by varenius** [comment]
> Are you using `export FESH_BKG_METHOD=ftp` on Oe/Ow and not on On?

Neither, I did not define method so I assumed it would use ftp-ssl for all machines by default.

**Comment by wehimwich** [comment]
"Too obvious I suppose" said the gigantic heavy-duty battle machine. Plain old ftp has been disabled anyway.

I got the same error here. When I hacked it to enable _curl_'s verbose output I got:

```
$ fesh -D bkg r11100
[fesh 2022-04-30]
Fetching schedule from server...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying xxx.xxx.xxx.29...
* TCP_NODELAY set
* Connected to ivs.xxx.xxx.xxx (xxx.xxx.xxx.29) port 21 (#0) 
< 530 connect failed: Host is down. No response from server.
* Got a 530 ftp-server response when 220 was expected
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (8) Got a 530 ftp-server response when 220 was expected
```

Which seems to imply the host is down, but that seems unlikely since On works.

I have emailed Markus to see if he knows what is happening.

Hmm. Maybe _fesh_ should have a command line option to enable verbose output in _curl_.

**Comment by wehimwich** [comment]
The answer came back that BKG is down since May 12 for an indefinite period. There was an email about this that I had forgotten. It is curious that On is reaching BKG. Can you confirm that?

I suppose this strengthens the case for a verbose option.

**Comment by wehimwich** [comment]
Maybe On is pointed to CDDIS or OPAR. You can force it to use BKG with `-D bkg`.

**Comment by varenius** [comment]
Indeed On was missing the line "export FESH_DATA_CENTER" in .profile - apologies, too little sleep and too many FS to compare ;). But this explains that problem. Trying bkg instead it indeed fails also for On. So issue explained, thanks.

Adding a -v option to fesh would be nice for similar errors. I leave it to @wehimwich if you want to do this here, or close this and open a new ticket for that.

**Comment by wehimwich** [comment]
No problem. I think I can imagine why you are getting too little sleep ("the days are long, but the years are short").

I have renamed this issue so it is about adding such an option. The `-v`, `-V`, `-d`, and `-D` options are already in use. Since `-v` is for verbose output for _drudg_, I think it would reasonable to have that do double duty for _curl_/_wget_.
