### ISSUE TITLE
Question: How to upload FS log files to CDDIS?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#202]
OSO has used BKG to upload FS log files. With recent BKG failure, this is no longer working. I want to switch to CDDIS. In the past, we have used a python script with lftp command to upload logfile. Is there a recommended way to upload logfiles using FS tools to CDDIS?

**Comment by jvrgnzlz** [comment]
At Yebes, we routinely use the FS tool "plog" to upload log files to CDDIS via curl

**Comment by varenius** [comment]
> 

Thanks, that was what I was looking for! I knew I had seen that. What parameters do you typically use?

**Comment by jvrgnzlz** [comment]
"plog -l" with the proper env-var set to CDDIS. We have a line to call the tool inside the "sched_end" procedure in station.prc, only care is to put it after changing to station's log (log=station)

**Comment by varenius** [comment]
Right, thanks. I will probably go for something more explicit, since there may be other logfiles interferring with the "-l" (e.g. vcc), so a call in a procedure like:
```
" Upload log to IVS server using details in /usr2/oper/.profile and .netrc
sy=/usr2/fs/bin/plog -z /usr2/log/`lognm`.log &
```
Will try and see.

Do you have a personal CDDIS account that you use for .netrc login details, or some general account (not sure if possible)?

**Comment by wehimwich** [comment]
For CDDIS you need individual accounts. The procedure for getting credentials for CDDIS upload is at:

https://cddis.nasa.gov/About/CDDIS_File_Download_Documentation.html

OPAR is less arduous.  The IVS site with instructions for OPAR and CDDIS uploads is:

https://ivscc.gsfc.nasa.gov/products-data/submit-data.html#http

**plog -h** has information on configuring _plog_,  but feel free to ask questions.

**Comment by varenius** [comment]
Thank you for all advice. I acknowledge -h gives very helpful instructions, but I was just curious to know what Yebes used. Anyway, I'm happy as is and closing this. Thanks again.

**Comment by wehimwich** [comment]
As @jvrgnzlz mentioned it is important to close the log first. When `plog -z` (but also with the `-z`, which is the intended usage) compresses the log, it will be renamed. When the FS eventually closes the log, it will detect that the original directory entry no longer exists and create a new copy before closing. That isn't too bad, but it will create a redundant copy with the original name. Also you might like to send the "complete" file.

You should be able to close the log in `sched_end`, but then _lognm_ won't do what you want. You could run a script with `sy=...` (with `&`?) that will capture the log name, close it (**inject_snap -w  log=station**), then run _plog_ with the name. Usually `-l` would make this subterfuge unnecessary, it avoids _station.log_ and _point.log_. If there is a new type it should avoid, we can add it (please let me know). OTOH, if you have just closed the experiment log, that should be what `-l` picks.

**Comment by wehimwich** [comment]
Without `-z` is the intended usage

**Comment by varenius** [comment]
Thank you for all good advice. I was mainly concerned about the "vvc.log" which in a previous version would reside in /usr2/log/vcc.log, and being updated by vcc on some unpredicted timescale it could interfere. However, Marco since changed the location to another directory, so it's no worry anymore. 

I also realised that we have been sending the logfile before switching to station.log before. We have had some mysterious cases with truncated logfiles, which I now believe could be due to the FS perhaps not fully flushing the log buffer to disk before we executed the lftp upload to BKG. So, again, following the advice given here and in plog -h, I have swapped for OSO logs to be uploaded with plog -l _after_ changing to station.log.

Many thanks!

**Comment by wehimwich** [comment]
This is just an addenda to clarify some misstatements I made.

1. _plog_ will detect if a log that will be compressed  (i.e., it contains multicast data) is open to the FS. If so, it will stop with an error message rather than renaming the log. So **plog -l** will just fail outright in that case.
2. In FS _10.0_, using **plog -z** was necessary to send (just) the compressed full log. Starting with  FS _10.1_, both a reduced version (without multicast data) and the full compressed log (with multicast data) will be sent without using `-z`. The IVS data centers apparently want both. You could just send one or the other with `-r` or `-z`, but the default in _10.1_ is to send both. This is not a consideration for stations without multicast, just the plain log will be sent.
3. After looking at the code,  `-l` will also not send a log with a name that doesn't end with the station's two letter code. I'll fix the `-h` output to reflect that. Requiring the two letter code is an additional safeguard, but maybe if VCC makes its own, non-FS, logs they should go in a sub-directory.
