### ISSUE TITLE
Restore -b command line option (but not -f)

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fs#216]
Christian at AGGO notes that the removal of the `-b` option from the _fs_ program removed the ability to start the FS entirely in background when the server is use. While the `-n` (or `--no-x`) option will not start any X11 windows, it still leaves the log output coming to `stdout`.

It seems like it is worth restoring the `-b` option since it offers additional functionality. OTOH, it doesn't seem like restoring the `-f` option is worthwhile, since this just disables use of the display server. Setting the environment variable `FS_DISPLAY_SERVER` to `off` accomplishes the same thing. It is not clear that providing a command line override  is worthwhile. Please speak up if you have a different opinion.

**Comment by BeppeMc** [comment]
Me too was used to launch FS in background (-b), option recently disappeared.
But I haven't see any problem to use the -n (no X) option to start FS.

It is true that FS outputs goes to stdout but with a CTR+C , window get gently closed with "client disconnected"
messages, apparently w/o any problem. And could be still reopened any time with fsclient -sn.

So I could not see the advantage of a restored -b option. Instead, it is better now, because at FS launch it is
important/mandatory to see that everything goes up w/o problems, now possible through the stdout window.

**Comment by wehimwich** [comment]
It is good point that you don't any feedback that it started correctly with `-b`. Since, as you say, you can Control-C to close the client after is starts, I thought `-b` was not needed. OTOH, `-b` provides additional functionality: starting the FS in server mode completely non-interactively. If people want to take that risk, I guess it is up to them. I can add something terse about it being risky to the `-h` output.

I think the description of the option could be improved in another way, and maybe renamed. Calling it `background` makes it seem like the inverse of `foreground`, whereas it is more specifically starting the FS with no client. So the `-h` output might say that. A different option could be used, maybe `-C` (_not_ client). Of course, it is unavailable if you aren't using server mode.
