### ISSUE TITLE
Spurious chars in ONOFF output

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#53]
Using commit fbd0133b0953b344d698254d8547a60010ea4cce :
The ONOFF VAL and SIG lines appar OK, but others have a spurious char inserted after #onoff#, for example:
```
2020.171.07:34:20.63#onoff#ðAPR ih     9552.00 1.573  371.67  0.027000 1.00000  0.027000 11600.00 p 0.16620
[...]
2020.171.07:36:07.12#onoff#¶ONSC   104.0   0.00000   0.00000 ig     2399.0      1.4 ih     2570.0      4.2
```
Is this correct? Please see attached logfile [dc6.log](https://github.com/nvi-inc/fs/files/4803202/dc6.log). Again, it doesn't happen for the VAL or SIG lines, but for the others.

**Comment by wehimwich** [comment]
Hi Eskil,

This baffles me. It does not happen at either KPGO 20m or 12m (we have no other testers with antennas so far, except you). None of the relevant  code has changed since the versions KPGO are running, 229f696ea124a8b495935bc0ad0f64a68261b266 (12m) and 10396864bf19aa3f87cdf5b0061064d484b0f500 (20m) . The code is structured so that the operations should be the same for `VAL`/`SIG` compared to other records. The code seems to be pretty straightforward in this regard.  If it is in the code anywhere, it is most likely in _poclb/logit.c_. 

I am not labelling this as "cosmetic" because if the spurious character was a new-line. it would cause  a problem for _gndat_ (the only downstream user of this data), even though it uses `strstr(line,"APR")` to find the `APR` records.

if you have time, just as a shot in the dark, could you please try (as `prog` at a shell `$` prompt):

```
 $ cd /usr2/fs
 $ make rmdoto rmexe
 $ make >&/dev/null
 $ make -s                     #no news is good news
```
(you could rebuild your station software from scratch as well, but that should not be necessary)

reboot and try again?

Thanks, Ed

**Comment by varenius** [comment]
Tried
```
prog@njord:/usr2/fs-git$ git checkout master
[...]
prog@njord:/usr2/fs-git$ git pull
[...]
prog@njord:/usr2/fs-git$ git rev-parse HEAD
```
which shows I'm using the latest de9dd2ab8b11ec858488b46e4901bd0967843f74
```
prog@njord:/usr2/fs-git$ make rmdoto rmexe
rm -f `find . -name '*.[oas]' -print`
rm -rf oprin/readline-2.0
rm -f `find . -name '*.pyc' -print`
rm -rf third_party/include third_party/lib third_party/bin
find third_party/src/* \
	! -iname '*.tar.gz' \
	! -iname '*.make' \
	! -iname '*.template' \
	-delete
rm -fr bin/*
prog@njord:/usr2/fs-git$ make >&/dev/null
prog@njord:/usr2/fs-git$ make -s
```
and then "reboot". Didn't work, still spurious char as before (i.e. not before VAL/SIG lines). Also tried
```
cd /usr2/st
make rmdoto rmexe
make
reboot
```
... but still the same problem. 

Note: Originally I got different spurious chars. In my few tries this mroning, I always got the "?" char (except for VAL/SIG lines). Not sure if this means anything.

Weird bug, this one!

**Comment by wehimwich** [comment]
Found it. Whew! It was a bug I introduced in 651701a6c, a really dumb error. I have left the fix (unstaged) in _poclb/logit.c_ on your machine and your FS remade so you can use it. I will introduce it as a commit on `master` shortly. Frankly, I am surprised that it wasn't apparent for other users and more apparent in general, but it is entirely my fault.

I didn't want to mess with your unstaged and untracked files.  It looks to me like they are related to Mikael's version of _ibcon_. We can look into getting that merged into the FS if you all would like. In the meantime, we could at least include the changes to `boss/rdtib.f`; they look entirely backward compatible. That way you won't have to re-update it when there is a new FS release. Life is easier if the working directory is clean. :)

In the meantime. I would encourage moving Mikael's version of _ibcon_ to _/usr2st_, for the same reason. The only revisions necessary for that should be to change the `..` references in the Makefile to `../../fs`, the same change to include file references in the code, and  to add it to _/usr/st/Makefile_. OTOH, if the _ibcon_ changes are backward compatible, maybe they could be merged in first.  It make be a little while until there is a chance though since we have to be really sure they are backward compatible. We could also put it on another branch initially.

Just as aside,  I noticed that you said that you were testing with fbd0133, which was actually before `-beta1` and before the erroneous commit. Maybe that was the last version you tried before `-beta1`. According to the log you attached, [dc6.log](https://github.com/nvi-inc/fs/files/4803202/dc6.log), you were testing with 7c2a0b11 (`-beta1-97-g7c2a0b11-dirty`), which doesn't seem to be on `master`. Maybe it was a local commit, but at 97 commits after `-beta1` it is almost certainly after the bad commit which was 21 commits after `-beta1`. This didn't confuse the debugging process in anyway, but I noticed it as I traced the trail of my error. Thank you for testing with `master` and I apologize for the bug.

**Comment by dehorsley** [comment]
This is a good argument for using a code formatter :)

**Comment by wehimwich** [comment]
I am game. The one thing I have never really recovered from by leaving _emacs_ was losing its indentation features (otherwise I like _vim_ much more), but we are discussing indentation on a different thread.
