### ISSUE TITLE
Question about IF= syntax and ONOFF cont_cal behaviour

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#54]
I tried running ONOFF with cont_cal=on. Doing this on the 9.12.12 system works, I think because the relevant procedures are defined as
```
define  caloffnf      20128155358
caloff
sy=go onoff &
!+1s
sy=go onoff &
enddef
define  calonnf       20128155406
calon
sy=go onoff &
!+1s
sy=go onoff &
enddef
```
However, following the recommendations in "/usr2/fs-git/help/onoff.___" , I have now (for FS10) defined these as
```
define  calonnf       20171074921
if=cont_cal,,calon
!+1s
sy=rte_go onoff &
enddef
define  caloffnf      20171074911x
if=cont_cal,,caloff
!+1s
sy=rte_go onoff &
enddef
```
I don't remember the logic for the IF statements (is this documented somewhere?), i.e. which call is excecuted if true/false. 

I assume from the behaviour in [dc6.log](https://github.com/nvi-inc/fs/files/4803203/dc6.log) that with cont_cal enabled, I don't get any useful tcal signal for the DBBC3. Likely the work in #32 needs to be finished first? Assuming this is the case, I turned cont_cal=off and tried again. Indeed, I now get reasonable values, see attached [dc7.log](https://github.com/nvi-inc/fs/files/4803203/dc7.log). Should I get reasonable values also with cont_cal enabled? Perhaps I am missing something somewhere?

**Comment by wehimwich** [comment]
Hi Eskil,

The _if_ command, like all SNAP commands, should be documented in its help page, for example in the FS input window (_oprin_) enter **`help=if`**.

With continuous cal on (set with **`cont_cal=on`**), _onoff_ ( and _fivept_) should not run the _calonnf_/_caloffnf_ (and _calonfp_/_calofffp_) procedures. Thus, the contents should not matter for continuous cal in 9.13.2 (or 10.0.0).

I don't think this is related to #32. We don't want to use multicast for _onoff_ (or _fivpt_) because it is not a reliable protocol. We learned that the hard way. Maybe there is some other issue I am not aware of though.

The snippet in your example in #52  (and _dc6.log_) shows:

> 2020.170.06:43:01.57;caloffnf
2020.170.06:43:01.57&caloffnf/if=cont_cal,,caloff
2020.170.06:43:01.57&caloffnf/!+1s
2020.170.06:43:01.57&caloffnf/sy=rte_go onoff &
2020.170.06:43:01.57&caloff/sy=popen 'noise_force 0 2>&1' -n noise
2020.170.06:43:01.61#popen#noise/!cal_noise_force=0:0;
2020.170.06:43:03.61#popen#noise/Set noise_force 0

This would suggest you did not have continuous cal on before you ran _onoff_ since it ran the _caloffnf_ procedure. That is a bug if you did have continuous cal on. There is no _cont_cal=..._ embedded that I could see in supplied log entries, so it is hard to be sure. This would usually mean it is _off_, but it may be in some other log. Can you confirm which way it was?

The more I think about it, I think the _if=cont_cal,,_ portions  in the _calon_/_off_ _nf_/_fp_ procedures are not needed. I will continue to think about this and may remove them when we close this issue.

If you only use continuous cal, you can select it in your _initp_ procedure (which you always run before _aquir_/_fivpt_/_onoff_, right?) to make sure it is alway on and never change it. The situation is a little more complicated when you switch back and forth between continuous and non-continuous cal with _fivpt_ and _onoff_ rather than just using one or the other.  This might be needed because some receivers support continuous cal and others do not or maybe sometimes it is useful to use non-continuous cal because the cal is stronger.

To switch back and forth, the best (simplest?) approach is probably to set it explicitly in _initp_ and have different setups for _aquir_ for each case. This can be a good match for changing set-ups for different receivers. It may require redundant _aquir_ setups to occasionally use non-continuous cal for receivers that havr continuous cal.

Alternatively, if you want to sometimes use non-continuous cal even for a receiver that has continuous cal, you could have _initp_ be independent of cal setup. Then the setup can be changed by a manually run SNAP procedure. That can save the setup with the SNAP _save_file_ as a SNAP command (or procedure) to be re-executed in the _initi_ procedure when the FS is restarted. This has the weakness that if the continuous cal selection is changed by a VLBI observation, its setup will not have been recorded in the "saved" file. This can be overcome by having the command (or procedure) be re-executed in the _initp_ procedure as well; however, it may _not_ agree with what is used in the VLBI observation.

The final tweak on this approach is to also have a manual receiver change SNAP procedure that will use the "saved" file to save the correct cal setup command (or procedure) in addition to the manual cal setup procedures. Again, it may not agree with what is used in the VLBI observation.

If it is helpful (and not too complicated), I may add something like this description to the _fivept_ and _onoff_ help files when we close this issue.

Thanks, Ed

**Comment by varenius** [comment]
Thank you for the "help=if" command; I see the syntax is "if=test,true,false". As a quick test, I thought I could try "if=cont_cal,ifa,ifb" which would run "ifa" if cont_cal is enabled, and "ifb" if not.  Starting with cont_cal=off...
```
2020.174.09:25:30.46;cont_cal
2020.174.09:25:30.48/cont_cal/off,2,80,0,10
2020.174.09:25:49.22;if=cont_cal,ifa,ifb
2020.174.09:25:49.22;ifb
2020.174.09:25:49.25/ifb/1,agc,32000,33251
```
so far so good. However:
```
2020.174.09:25:56.57;cont_cal=on
2020.174.09:26:05.67;cont_cal
2020.174.09:26:05.69/cont_cal/on,2,80,0,10
2020.174.09:26:08.65;if=cont_cal,ifa,ifb
2020.174.09:26:08.65;ifb
2020.174.09:26:08.80/ifb/1,agc,32000,32175
```
Still seems to run "ifb". It should run "ifa", right?

**Comment by wehimwich** [comment]
This was that `if=cont_cal,...` had not been implemented for DBBC3 racks. The DBBC3 support isn't complete yet, but it is easy to add this. There will be a closing commit shortly.
