### ISSUE TITLE
dbbc3 dsc_tp multiline output mismatch

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#75]
This happens on both OSO computer fulla (FS 9.12.12 VGOS) and OSO computer njord (FS 10 which I think runs 0cb92e556142a6751a5ef42c85e10d608562181e i.e. last version tested there by Ed). The problem is that the last line of response is missing "#dbbcn#":
```
2020.309.11:43:41.66;dbbc3=dsc_tp=1
2020.309.11:43:41.69#dbbcn#dbbc3/dsc_tp/
2020.309.11:43:41.69#dbbcn#dbbc3/TP[1][0] = 59757486
2020.309.11:43:41.69#dbbcn#dbbc3/TP[1][1] = 60791369
2020.309.11:43:41.69#dbbcn#dbbc3/TP[1][2] = 61597149
2020.309.11:43:41.69/dbbc3/TP[1][3] = 62179397;
```

The last line should instead be, I guess,
`2020.309.11:43:41.69#dbbcn#dbbc3/TP[1][3] = 62179397;`

So I guess there is some counter somewhere which is "i" and should be "i+1" ?

**Comment by wehimwich** [comment]
Actually, it this way by design for all multi-line FS `dbbc3` (and `dbbc`) command output for the DBBC3 (and DBBC2). But one could argue it is not a good design. :) For multi-line output, all except the last line is reported by _dbbcn_ to avoid possibly having too large a chunk of data to pass between programs internally in one go. This prevents there being a limit on the number of lines that can be handled. Having the final line reported by the `dbbc3` command is intended to make it clear that the device response has terminated (and if no error is reported, terminated cleanly). It also matches the style of single-line responses which just appear as a single `dbbc3/` output line. In principle, the low-level device commands like `dbbc3` are only intended for debugging.

My first reaction is to not change this. I'll leave this issue open for awhile in case you want to comment further. If you think it is finished, please feel free close it.

**Comment by varenius** [comment]
Ahaaaa. I see, so the hashes indicate an continued output, and then the last line is the end. Gotcha. 

I think this can be left as is. I agree it is more of a feature than a bug, now that I know the reason for it :).

**Comment by wehimwich** [comment]
Fair enough issue, especially since it was not documented. :) I have pushed an update that describes the response in the `help` file for the `dbbc` command and adds `help` for the `dbbc2` and `dbbc3` commands (they all use the same file). Thanks.
